version: 2
updates:
  - package-ecosystem: nuget
    directory: /Premium
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    groups:
      avalonia:
        patterns:
          - Avalonia
          - Avalonia.*
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: Avalonia*
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
