using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace UsfmIntegrityStudio.Models;

public sealed record BttwProjectPackageResult(
    string UsfmPath,
    string TstudioPath,
    string ProjectId,
    int ChapterCount,
    int ChunkCount);

public static class BttwProjectPackageService
{
    private const string GeneratorName = "ts-desktop";
    private const string GeneratorBuild = "1073x";
    private static readonly Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
    private static readonly Regex VerseMarkerRegex = new(@"\\v\s+(\d+)\s*", RegexOptions.Compiled | RegexOptions.CultureInvariant);
    private static readonly Dictionary<string, string> EnglishBookNames = new(StringComparer.OrdinalIgnoreCase)
    {
        ["GEN"] = "Genesis", ["EXO"] = "Exodus", ["LEV"] = "Leviticus", ["NUM"] = "Numbers", ["DEU"] = "Deuteronomy",
        ["JOS"] = "Joshua", ["JDG"] = "Judges", ["RUT"] = "Ruth", ["1SA"] = "1 Samuel", ["2SA"] = "2 Samuel",
        ["1KI"] = "1 Kings", ["2KI"] = "2 Kings", ["1CH"] = "1 Chronicles", ["2CH"] = "2 Chronicles",
        ["EZR"] = "Ezra", ["NEH"] = "Nehemiah", ["EST"] = "Esther", ["JOB"] = "Job", ["PSA"] = "Psalms",
        ["PRO"] = "Proverbs", ["ECC"] = "Ecclesiastes", ["SNG"] = "Song of Songs", ["ISA"] = "Isaiah",
        ["JER"] = "Jeremiah", ["LAM"] = "Lamentations", ["EZK"] = "Ezekiel", ["DAN"] = "Daniel",
        ["HOS"] = "Hosea", ["JOL"] = "Joel", ["AMO"] = "Amos", ["OBA"] = "Obadiah", ["JON"] = "Jonah",
        ["MIC"] = "Micah", ["NAM"] = "Nahum", ["HAB"] = "Habakkuk", ["ZEP"] = "Zephaniah", ["HAG"] = "Haggai",
        ["ZEC"] = "Zechariah", ["MAL"] = "Malachi", ["MAT"] = "Matthew", ["MRK"] = "Mark", ["LUK"] = "Luke",
        ["JHN"] = "John", ["ACT"] = "Acts", ["ROM"] = "Romans", ["1CO"] = "1 Corinthians", ["2CO"] = "2 Corinthians",
        ["GAL"] = "Galatians", ["EPH"] = "Ephesians", ["PHP"] = "Philippians", ["COL"] = "Colossians",
        ["1TH"] = "1 Thessalonians", ["2TH"] = "2 Thessalonians", ["1TI"] = "1 Timothy", ["2TI"] = "2 Timothy",
        ["TIT"] = "Titus", ["PHM"] = "Philemon", ["HEB"] = "Hebrews", ["JAS"] = "James", ["1PE"] = "1 Peter",
        ["2PE"] = "2 Peter", ["1JN"] = "1 John", ["2JN"] = "2 John", ["3JN"] = "3 John", ["JUD"] = "Jude",
        ["REV"] = "Revelation"
    };

    public static IReadOnlyList<BttwProjectPackageResult> PackageDirectory(string outputDirectory, string languageCode)
    {
        if (!Directory.Exists(outputDirectory))
        {
            return [];
        }

        var results = new List<BttwProjectPackageResult>();
        foreach (var usfmPath in Directory.GetFiles(outputDirectory, "*.usfm", SearchOption.TopDirectoryOnly)
                     .OrderBy(path => path, StringComparer.OrdinalIgnoreCase))
        {
            results.Add(PackageUsfm(usfmPath, languageCode));
        }

        return results;
    }

    public static BttwProjectPackageResult PackageUsfm(string usfmPath, string languageCode)
    {
        var parsed = ParseUsfm(usfmPath);
        var lang = NormalizeLanguageCode(languageCode);
        var projectFolderName = $"{lang}_{parsed.BookId.ToLowerInvariant()}_text_{parsed.ResourceId}";
        var outputPath = Path.Combine(
            Path.GetDirectoryName(Path.GetFullPath(usfmPath)) ?? Directory.GetCurrentDirectory(),
            $"{projectFolderName}.tstudio");

        var tempRoot = Path.Combine(Path.GetTempPath(), $"uis-bttw-package-{Guid.NewGuid():N}");
        try
        {
            Directory.CreateDirectory(tempRoot);
            var projectRoot = Path.Combine(tempRoot, projectFolderName);
            Directory.CreateDirectory(projectRoot);
            Directory.CreateDirectory(Path.Combine(projectRoot, "front"));
            File.WriteAllText(Path.Combine(projectRoot, "front", "title.txt"), parsed.Title + Environment.NewLine, Utf8NoBom);
            File.WriteAllText(Path.Combine(projectRoot, "LICENSE.md"), "Generated by UIS Premium." + Environment.NewLine, Utf8NoBom);

            var finishedChunks = new List<string> { "front-title" };
            foreach (var chapter in parsed.Chapters.OrderBy(chapter => chapter.Number))
            {
                var chapterId = FormatNumber(chapter.Number);
                var chapterDir = Path.Combine(projectRoot, chapterId);
                Directory.CreateDirectory(chapterDir);
                File.WriteAllText(Path.Combine(chapterDir, "title.txt"), chapter.Title + Environment.NewLine, Utf8NoBom);
                finishedChunks.Add($"{chapterId}-title");

                foreach (var chunk in BuildBttwChunks(parsed.BookId, chapter))
                {
                    var verseId = FormatNumber(chunk.Verse);
                    File.WriteAllText(Path.Combine(chapterDir, $"{verseId}.txt"), chunk.Content.Trim() + Environment.NewLine, Utf8NoBom);
                    finishedChunks.Add($"{chapterId}-{verseId}");
                }
            }

            var targetLanguage = BuildTargetLanguage(lang, parsed.IsRtl);
            var innerManifest = new
            {
                package_version = 8,
                format = "usfm",
                generator = new { name = GeneratorName, build = GeneratorBuild },
                target_language = targetLanguage,
                project = new { id = parsed.BookId.ToLowerInvariant(), name = parsed.ProjectName },
                type = new { id = "text", name = "Text" },
                resource = new { id = parsed.ResourceId, name = parsed.ResourceName },
                source_translations = new[]
                {
                    new
                    {
                        language_id = "en",
                        resource_id = "ulb",
                        checking_level = "3",
                        date_modified = 20170329,
                        version = "9"
                    }
                },
                parent_draft = new { },
                translators = Array.Empty<string>(),
                finished_chunks = finishedChunks
            };

            File.WriteAllText(
                Path.Combine(projectRoot, "manifest.json"),
                JsonSerializer.Serialize(innerManifest, JsonOptions()) + Environment.NewLine,
                Utf8NoBom);

            var outerManifest = new
            {
                generator = new { name = GeneratorName, build = GeneratorBuild },
                package_version = 2,
                timestamp = DateTimeOffset.Now.ToUnixTimeMilliseconds(),
                target_translations = new[]
                {
                    new
                    {
                        path = projectFolderName,
                        id = projectFolderName,
                        commit_hash = new { stdout = string.Empty, stderr = string.Empty, error = (string?)null },
                        direction = targetLanguage.direction
                    }
                }
            };

            File.WriteAllText(
                Path.Combine(tempRoot, "manifest.json"),
                JsonSerializer.Serialize(outerManifest, JsonOptions()) + Environment.NewLine,
                Utf8NoBom);

            if (File.Exists(outputPath))
            {
                File.Delete(outputPath);
            }

            ZipFile.CreateFromDirectory(tempRoot, outputPath, CompressionLevel.Optimal, includeBaseDirectory: false);
            return new BttwProjectPackageResult(
                usfmPath,
                outputPath,
                parsed.BookId,
                parsed.Chapters.Count,
                parsed.Chapters.Sum(chapter => BuildBttwChunks(parsed.BookId, chapter).Count));
        }
        finally
        {
            try
            {
                if (Directory.Exists(tempRoot))
                {
                    Directory.Delete(tempRoot, recursive: true);
                }
            }
            catch
            {
                // Temp cleanup should not invalidate a successful package.
            }
        }
    }

    private static ParsedUsfm ParseUsfm(string usfmPath)
    {
        var lines = File.ReadAllLines(usfmPath, Encoding.UTF8);
        var bookId = "UNK";
        var resourceName = "Regular";
        var title = string.Empty;
        var resourceId = "reg";
        var chapters = new List<ParsedChapter>();
        ParsedChapter? currentChapter = null;

        foreach (var rawLine in lines)
        {
            var line = rawLine.Trim();
            if (line.Length == 0)
            {
                continue;
            }

            if (line.StartsWith("\\id ", StringComparison.Ordinal))
            {
                var parts = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                if (parts.Length >= 2)
                {
                    bookId = parts[1].Trim().ToUpperInvariant();
                }

                if (parts.Length >= 3)
                {
                    resourceName = string.Join(' ', parts.Skip(2)).Trim();
                    resourceId = string.Equals(resourceName, "Regular", StringComparison.OrdinalIgnoreCase)
                        ? "reg"
                        : SanitizeId(resourceName);
                }

                continue;
            }

            if (line.StartsWith("\\h ", StringComparison.Ordinal)
                || line.StartsWith("\\toc1 ", StringComparison.Ordinal)
                || line.StartsWith("\\mt ", StringComparison.Ordinal))
            {
                if (string.IsNullOrWhiteSpace(title))
                {
                    title = line[(line.IndexOf(' ') + 1)..].Trim();
                }

                continue;
            }

            if (line.StartsWith("\\c ", StringComparison.Ordinal))
            {
                if (int.TryParse(line[3..].Trim(), out var chapterNumber) && chapterNumber > 0)
                {
                    currentChapter = new ParsedChapter(chapterNumber, string.Empty, []);
                    chapters.Add(currentChapter);
                }

                continue;
            }

            if (line.StartsWith("\\cl ", StringComparison.Ordinal) && currentChapter is not null)
            {
                currentChapter.Title = line[4..].Trim();
                continue;
            }

            if (!line.StartsWith("\\v ", StringComparison.Ordinal) || currentChapter is null)
            {
                continue;
            }

            foreach (var chunk in SplitVerseChunks(line))
            {
                currentChapter.Chunks.Add(chunk);
            }
        }

        if (string.IsNullOrWhiteSpace(title))
        {
            title = bookId;
        }

        foreach (var chapter in chapters)
        {
            if (string.IsNullOrWhiteSpace(chapter.Title))
            {
                chapter.Title = IsLikelyRtl(title) ? $"باب {chapter.Number}" : $"Chapter {chapter.Number}";
            }
        }

        var projectName = EnglishBookNames.GetValueOrDefault(bookId, bookId);
        return new ParsedUsfm(bookId, title, projectName, resourceId, resourceName, IsLikelyRtl(string.Join('\n', lines)), chapters);
    }

    private static IEnumerable<ParsedChunk> SplitVerseChunks(string line)
    {
        var matches = VerseMarkerRegex.Matches(line);
        for (var i = 0; i < matches.Count; i++)
        {
            var match = matches[i];
            if (!int.TryParse(match.Groups[1].Value, out var verse) || verse <= 0)
            {
                continue;
            }

            var start = match.Index + match.Length;
            var end = i + 1 < matches.Count ? matches[i + 1].Index : line.Length;
            var content = line[start..end].Trim();
            if (content.Length > 0)
            {
                yield return new ParsedChunk(verse, content);
            }
        }
    }

    private static IReadOnlyList<ParsedChunk> BuildBttwChunks(string bookId, ParsedChapter chapter)
    {
        var verses = chapter.Chunks
            .OrderBy(chunk => chunk.Verse)
            .ToList();
        if (verses.Count == 0)
        {
            return [];
        }

        if (!BttwCanonicalChunkMap.TryGetChapterStarts(bookId, chapter.Number, out var starts))
        {
            return verses
                .Select(chunk => new ParsedChunk(chunk.Verse, EnsureLeadingVerseMarker(chunk.Verse, chunk.Content)))
                .ToList();
        }

        var groupedByCanonicalStart = new SortedDictionary<int, List<ParsedChunk>>();
        foreach (var verse in verses)
        {
            if (!BttwCanonicalChunkMap.TryFindChunkStart(bookId, chapter.Number, verse.Verse, out var canonicalStart))
            {
                throw new InvalidDataException(
                    $"Verse {bookId} {chapter.Number}:{verse.Verse} cannot be assigned to the canonical BTTW chunk map.");
            }

            if (!groupedByCanonicalStart.TryGetValue(canonicalStart, out var group))
            {
                group = [];
                groupedByCanonicalStart[canonicalStart] = group;
            }

            group.Add(verse);
        }

        return groupedByCanonicalStart
            .Select(group => new ParsedChunk(
                group.Key,
                string.Join(" ", group.Value.Select(chunk => EnsureLeadingVerseMarker(chunk.Verse, chunk.Content)))))
            .ToList();
    }

    private static string EnsureLeadingVerseMarker(int verse, string content)
    {
        var trimmed = content.Trim();
        return VerseMarkerRegex.IsMatch(trimmed)
            ? trimmed
            : $"\\v {verse} {trimmed}";
    }

    private static TargetLanguage BuildTargetLanguage(string languageCode, bool isRtl)
    {
        var name = languageCode switch
        {
            "skr" => "سرائیکی",
            "urd" or "ur" => "اردو",
            "rus" or "ru" => "Russian",
            _ => languageCode
        };

        return new TargetLanguage(languageCode, name, isRtl ? "rtl" : "ltr");
    }

    private static string FormatNumber(int value) => value <= 99 ? value.ToString("00") : value.ToString();

    private static string NormalizeLanguageCode(string languageCode)
    {
        return string.IsNullOrWhiteSpace(languageCode)
            ? "und"
            : SanitizeId(languageCode).ToLowerInvariant();
    }

    private static string SanitizeId(string value)
    {
        var chars = value
            .Trim()
            .Select(ch => char.IsLetterOrDigit(ch) ? char.ToLowerInvariant(ch) : '_')
            .ToArray();
        var sanitized = new string(chars).Trim('_');
        return string.IsNullOrWhiteSpace(sanitized) ? "reg" : sanitized;
    }

    private static bool IsLikelyRtl(string value)
    {
        return value.Any(ch => (ch >= '\u0600' && ch <= '\u06FF') || (ch >= '\u0750' && ch <= '\u077F'));
    }

    private static JsonSerializerOptions JsonOptions() => new() { WriteIndented = true };

    private sealed record ParsedUsfm(
        string BookId,
        string Title,
        string ProjectName,
        string ResourceId,
        string ResourceName,
        bool IsRtl,
        List<ParsedChapter> Chapters);

    private sealed record ParsedChapter(int Number, string Title, List<ParsedChunk> Chunks)
    {
        public string Title { get; set; } = Title;
    }

    private sealed record ParsedChunk(int Verse, string Content);

    private sealed record TargetLanguage(string id, string name, string direction);
}
